version: '3.6'

services:
  react:
    build:
      context: .
      dockerfile: ./react.Dockerfile
    image: react:v0.2
    working_dir: /app/
    container_name: react
    hostname: react
    domainname: "react.local"
    volumes:
      - ./app/:/app/:rw
      - ./docker-entrypoint.d/:/docker-entrypoint.d/
    ports:
      - 8000:8000
    entrypoint: ["sh", "/docker-entrypoint.d/react-server-entrypoint.sh"]
#    expose:
#      - 80
#    environment:
#      - PATH=/app/node_modules/.bin:$PATH
#      - VIRTUAL_HOST=react.local
#      - VIRTUAL_PORT=80
    networks:
      net_react_test:
      net_proxy_nginx:

networks:
  net_proxy_nginx:
    name: net_proxy_nginx
    external: true
  net_react_test:
    name: net_react_test
